steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend                         # ★必須：backend を作業ディレクトリに
    args: ['build','-t','${_IMAGE}:$SHORT_SHA','-f','Dockerfile','.']
  - name: gcr.io/cloud-builders/docker
    args: ['push','${_IMAGE}:$SHORT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ['run','deploy','${_SERVICE}',
           '--image=${_IMAGE}:$SHORT_SHA',
           '--region=${_REGION}',
           '--platform=managed',
           '--allow-unauthenticated',
           '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest']
substitutions:
  _REGION: 'asia-northeast1'
  _SERVICE: 'grow-backend'
  _IMAGE: '${_REGION}-docker.pkg.dev/$PROJECT_ID/containers/grow-backend'
options:
  logging: CLOUD_LOGGING_ONLY            # ★logs_bucketエラー回避
